### ISSUE TITLE
Trained Model

### ISSUE THREAD

**Issue by gan3sh500** [cad0p/maskrcnn-modanet#10]
Do you have a model already trained on Modanet I can try out? Otherwise I'm training one myself now. I was going to use another mask-rcnn implementation but I can use yours and PR with a trained model.

**Comment by gan3sh500** [comment]
Never mind I found your file in the download.sh. Thank you so much. It's very helpful. :)

**Comment by cad0p** [comment]
Hey! I'd love too see how you are using it, since my thesis presentation is
tomorrow and I could cite how it's already being used!

Thanks

Pier Carlo

**Comment by gan3sh500** [comment]
I’m writing it as a module in some demo. I don’t know the rest properly but when it’s done I’ll post here. Definitely won’t be done by tomorrow though. Anyway, good luck presenting. :)

**Comment by andytwoods** [comment]
cad0p, some serious skills here. Come and do a phd with us?! https://www.jobs.ac.uk/job/BTS535/phd-studentship-adding-senses-to-vr-ar-and-evaluating-sensory-audience-experiences 
Currently building an audience emotion CV app :)

**Comment by cad0p** [comment]
@andytwoods Hi, sorry for the late reply. 

Thanks a lot for the offer, but I just finished my bachelor's and I'd like to complete my education with a master's degree (I am applying to go to Politecnico di Milano in Italy starting this September). 

But let's keep in touch! I'm curious to see your work and I'll keep the offer for when I'll finish in Milan.
