### ISSUE TITLE
 Windows: No module named 'maskrcnn_modanet.cli'

### ISSUE THREAD

**Issue by andytwoods** [cad0p/maskrcnn-modanet#11]
Hi, 
having a play with your really awesome package. Encountering:
 No module named 'maskrcnn_modanet.cli'
Will feedback my go-arounds.
thanks,
Andy.

**Comment by cad0p** [comment]
Hi! This package is not tested for Windows!

There is also a bash script that would have to be changed to make it work
with Windows
