### ISSUE TITLE
No module named 'maskrcnn_modanet.cli'

### ISSUE THREAD

**Issue by rsumit123** [cad0p/maskrcnn-modanet#12]
I ran pip install maskrcnn-modanet on a gcp instance with linux and i am facing this error whenever i try to run any command 

`Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/python3/bin/maskrcnn-modanet", line 7, in <module>
    from maskrcnn_modanet.cli.main import main
ModuleNotFoundError: No module named 'maskrcnn_modanet.cli'`

**Comment by cad0p** [comment]
Try cloning the repo and installing from local

**Comment by rsumit123** [comment]
Tried it .. same error

**Comment by rsumit123** [comment]
It is successfully installing with no errors . But while running a command it is throwing the error

**Comment by cad0p** [comment]
It's very strange.. 

You should have this file, right?

https://github.com/cad0p/maskrcnn-modanet/blob/master/maskrcnn_modanet/cli/main.py


Try on the console to import maskrcnn_modanet and see if it fails

**Comment by cad0p** [comment]
A possible solution is detailed in here:

https://github.com/jvrsantacruz/mp3hash/issues/1#issuecomment-16350302

Maybe check if it solves your problem and if yes, pull request!

**Comment by rsumit123** [comment]
> It's very strange..
> 
> You should have this file, right?
> 
> https://github.com/cad0p/maskrcnn-modanet/blob/master/maskrcnn_modanet/cli/main.py
> 
> Try on the console to import maskrcnn_modanet and see if it fails

Yeah i have this file.. i tried to import maskrcnn-modanet from the python console and it is imported successfully

**Comment by rsumit123** [comment]
> A possible solution is detailed in here:
> 
> [jvrsantacruz/mp3hash#1 (comment)](https://github.com/jvrsantacruz/mp3hash/issues/1#issuecomment-16350302)
> 
> Maybe check if it solves your problem and if yes, pull request!

I could not understand what this solution is trying to say ? Is there a way i can train from inside the python script since it is importing successfully there

**Comment by rsumit123** [comment]
I am facing the same issue on every linux machine i have tried so far

**Comment by cad0p** [comment]
I'll try and do the fix for you on a new branch tonight, I'll let you know

**Comment by cad0p** [comment]
> I ran pip install maskrcnn-modanet on a gcp instance with linux and i am facing this error whenever i try to run any command
> 
> `Traceback (most recent call last): File "/home/ubuntu/anaconda3/envs/python3/bin/maskrcnn-modanet", line 7, in <module> from maskrcnn_modanet.cli.main import main ModuleNotFoundError: No module named 'maskrcnn_modanet.cli'`

running this from console fails right?
```
python3
from maskrcnn_modanet.cli.main import main
main()
```

**Comment by rsumit123** [comment]
Yes. Same error

**Comment by rsumit123** [comment]
`Python 3.7.3 (default, Mar 27 2019, 22:11:17)                                                                           [GCC 7.3.0] :: Anaconda, Inc. on linux                                                                                  Type "help", "copyright", "credits" or "license" for more information.                                                  >>> from maskrcnn_modanet.cli.main import main                                                                          Traceback (most recent call last):                                                                                        File "<stdin>", line 1, in <module>                                                                                   ModuleNotFoundError: No module named 'maskrcnn_modanet.cli'                                                             >>> import maskrcnn_modanet                                                                                             >>>   `

**Comment by cad0p** [comment]
ok I think I fixed it. let me know! f49f3ed81e5b1cf8f486b51440b6ee65a7f03cb9

**Comment by cad0p** [comment]
just checkout the branch here:

https://github.com/cad0p/maskrcnn-modanet/tree/with-no-module-cli-failed-install

**Comment by rsumit123** [comment]
I think it is working now .. Thanks very much bro..

**Comment by cad0p** [comment]
Let me know how you'll use the program! I'll merge into main branch 👍

**Comment by rsumit123** [comment]
I will try to train a MaskRcnn model from your program. Thanks Again
