### ISSUE TITLE
Can't load model weights.

### ISSUE THREAD

**Issue by enigmanx** [cad0p/maskrcnn-modanet#16]
When model loads get error:

ValueError: Cannot use 'roi_align_1/map/while/strided_slice_20' as input to 'roi_align_1/map/while/zeros/packed' because 'roi_align_1/map/while/strided_slice_20' is in a while loop. See info log for more details.

**Comment by cad0p** [comment]
@enigmanx how did you solve it? (Just in case someone else runs into this problem)

**Comment by luzer** [comment]
same!

**Comment by shreyjasuja** [comment]
use pip install keras==2.2.4
