### ISSUE TITLE
ValueError: Cannot use 'roi_align_1/map/while/strided_slice_20' 

### ISSUE THREAD

**Issue by luzer** [cad0p/maskrcnn-modanet#22]
`ValueError: Cannot use 'roi_align_1/map/while/strided_slice_20' as input to 'roi_align_1/map/while/zeros/packed' because 'roi_align_1/map/while/strided_slice_20' is in a while loop. See info log for more details.`
when running this
`maskrcnn-modanet processimage save image -u https://static.highsnobiety.com/thumbor/XZwWwq9iqiAHOblIR8Jqt5yuBis=/fit-in/1200x720/smart/static.highsnobiety.com/wp-content/uploads/2019/08/05125216/serbian-streetwear-scene-feat2.jpg`
LOVE this project

i am having lots of issues running locally
i have python 3.7
virtualenv
tensorflow downgraded to 1.13.1 for comaptability

**Comment by luzer** [comment]
this happens with the google collab notebook as well

**Comment by thebeyonder001** [comment]
Did you find any solution??

**Comment by 0xsimulacra** [comment]
Tensorflow=1.13.1 , keras==2.2.4, keras-retinanet==0.5.1
You might be needing to install tensorboard 1.15.0 and tensorflow-estimator 1.15.1 too. (they should still work with tf 1.13.1)

After that you do pip install -e . (if regular install still have the same problem)

This solved the same problem on colab for me. Beware sometimes on colab even if you specify the right keras version it doesn't install it but install the latest one so you should rerun the pip command again.

**Comment by cad0p** [comment]
All the correct versions are now in the last commit https://github.com/cad0p/maskrcnn-modanet/commit/38551c4ae684000a4c6f31c46c6912db5fdbe2c3
